### PR TITLE
add filter function

### PR DESCRIPTION
**Pull request by cheapsteak**
Is this what you had in mind? 
#2

### CODE REVIEW

**Comment by mattdesl** [comment]
Might be good to have the default alpha thresholding in place like this:
https://github.com/mattdesl/get-rgba-palette/blob/feature/filter/index.js

**Comment by mattdesl** [comment]
thanks though i can finish the PR from your stuff :)

**Comment by mattdesl** [comment]
you can see the docs / test:
https://github.com/mattdesl/get-rgba-palette/tree/feature/filter

**Comment by cheapsteak** [comment]
you do fast work :+1:

**Comment by mattdesl** [comment]
ok pushed to 2.0.0 since it presents a potential breaking change if any users were depending on the lib to not return white pixels

**Comment by cheapsteak** [comment]
good call

**Pull request closed without merging**
